### PR TITLE
Rename test_parser.py to test_parse.py

### PR DESCRIPTION
**Pull request by Sambit712**
### shader Sample
<!-- Provide a shader sample or snippet on which you have tested your changes. like

```crossgl
shader PerlinNoise {
    vertex {
        input vec3 position;
        output vec2 vUV;

        void main() {
            vUV = position.xy * 10.0;
            gl_Position = vec4(position, 1.0);
        }
    }

    // Perlin Noise Function
    float perlinNoise(vec2 p) {
        return fract(sin(dot(p, vec2(12.9898, 78.233))) * 43758.5453);
    }

    // Fragment Shader
    fragment {
        input vec2 vUV;
        output vec4 fragColor;

        void main() {
            float noise = perlinNoise(vUV);
            float height = noise * 10.0;
            vec3 color = vec3(height / 10.0, 1.0 - height / 10.0, 0.0);
            fragColor = vec4(color, 1.0);
        }
    }
}
```-->


### Checklist
- [ ] Have you added the necessary tests?
- [ ] Only modified the files mentioned in the related issue(s)?
- [ ] Are all tests passing?

### CODE REVIEW

**Review by samthakur587 — COMMENTED** [review]
why ?

**Comment by Sambit712** [comment]
Actually there was a problem regarding the code and the changes weren't
being accepted so I thought I might upload another file now it
worked.....thank you for the understanding sir

**Comment by samthakur587** [comment]
can you  please close this PR. @Sambit712

**Comment by Sambit712** [comment]
Sure! Sir

**Pull request closed without merging**
