### PR TITLE
Support for LOGICAL AND operator in DirectX backend

### LINKED ISSUE #183: LOGICAL_AND" : &&

### PR DESCRIPTION
**Pull request by gjyotin305**
### Summary

Adds LOGICAL_AND operator to DirectX Backend.

### Related Issue

closes #183

### Changes

Fixed `lexer.py` and `parser.py` for logical operators in DirectX Backend

### Shader Sample (Optional)

Example:
```crossgl
PSOutput PSMain(PSInput input) {
    PSOutput output;
    output.out_color = float4(0.0, 0.0, 0.0, 1.0);
    // Test case for logical AND
    bool condition1 = true; // First condition
    bool condition2 = false; // Second condition
    if (condition1 && condition2) {
        // both the condition is true
        output.out_color = float4(1.0, 0.0, 0.0, 1.0); // Set color to red
    } else {
        // any one of the condition is false
        output.out_color = float4(0.0, 1.0, 0.0, 1.0); // Set color to green
    }
    return output;
}
```

### Testing

Added 1 test for logical_AND operator in `test_directx`

### Checklist

- [x] Tests cover new or changed code (or reason why not)
- [x] Linked the issue with a closing keyword (if applicable)
- [x] Only touched files related to the issue
- [x] Everything builds and runs locally

### CODE REVIEW

**Comment by gjyotin305** [comment]
@NripeshN PTAL again

**Comment by gjyotin305** [comment]
Hi @NripeshN do you want me to solve issue #105 in this PR?

**Comment by NripeshN** [comment]
> Hi @NripeshN do you want me to solve issue #105 in this PR?

Hi @gjyotin305,
If you want add [LOGICAL AND](https://github.com/CrossGL/crosstl/issues/119) into the frontend feel free to do so. If you want to work on other issues in the ToDo issue list, please create a new PR. It would be easier to track changes this way😁

**Review by NripeshN — APPROVED** [review]
LGTM!!

**Comment by NripeshN** [comment]
Hey @gjyotin305, thanks for the duplicates. I've closed them in favor of #232. Feel free to collaborate by reviewing or suggesting changes here.

**Comment by NripeshN** [comment]
Couldn't add co-author commit. If you want them credited, you can add them manually.

Error:
```
Command '['git', 'commit', '--allow-empty', '-m', 'Add co-authors\n\nCo-authored-by: gjyotin305 <gjyotin305@users.noreply.github.com>\n']' returned non-zero exit status 128.
```

**Pull request merged**
