### PR TITLE
Added else if to translator #32

### LINKED ISSUE #32: Add `else if `  Conditional Statements to the translator
To add `else if` support to CrossGL, modify the following files in the `crosstl/src/translator` directory:

- [ ] **Lexer.py**: Add token recognition for `else if`.
- [ ] **Parser.py**: Update grammar and AST to handle `else if`.
- [ ] **Directx_codegen.py**: Implement `else if` for HLSL output.
- [ ] **Metal_codegen.py**: Implement `else if` for Metal output.
- [ ] **Opengl_codegen.py**: Implement `else if` for GLSL output. 

Your contribution is appreciated! Feel free to reach out on our [Discord Server ](https://discord.com/invite/uyRQKXhcyW) if you have any query.

### PR DESCRIPTION
**Pull request by AxelB1011**
Modified the following files in the crosstl/src/translator directory:

- [ ]  Lexer.py: We don't really need to add token recognition for else if.
- [x]  Parser.py: Similarly, we don't need to update grammar/AST. Updating the the parse_if_statement() function works.
- [x]  Directx_codegen.py: Implemented else if for HLSL output.
- [x]  Metal_codegen.py: Implemented else if for Metal output.
- [x]  Opengl_codegen.py: Implemented else if for GLSL output.
- [x] Added (naive, not sure if they're logically accurate) tests for multiple else if conditionals in test_translator and test_translator/test_codegen.
-  Please let me know of any other errors in this PR.

Closes #32

### CODE REVIEW

**Comment by AxelB1011** [comment]
@vaatsalya123  @samthakur587   Apologies, could you guys please review this PR? TIA!

**Review by samthakur587 — CHANGES_REQUESTED** [review]
Hii @AxelB1011 your changes are looking great to me can you just write tests for else_if . You can find the all test file at tests folder in test_translator .

**Comment by AxelB1011** [comment]
Hello @samthakur587, thank you for your feedback! I've made some changes, edited the description accordingly and the test cases are passing now. Although I'm not sure what to do with pre-commit.ci - pr...

**Comment by NripeshN** [comment]
> Hello @samthakur587, thank you for your feedback! I've made some changes, edited the description accordingly and the test cases are passing now. Although I'm not sure what to do with pre-commit.ci - pr...

Can you run _pre-commit run --all-files_ on your terminal. This should fix the error in CI

**Comment by AxelB1011** [comment]
Thank you @NripeshN, that worked

**Comment by samthakur587** [comment]
hii @AxelB1011 can you please sync your branch with latest changes. test files for codegen are not in pr.

**Review by samthakur587 — CHANGES_REQUESTED** [review]
hii @AxelB1011 there is no test files for codegen when i pulled your pr in my local can you please check and sync your branch with latest changes .

**Comment by AxelB1011** [comment]
> hii @AxelB1011 there is no test files for codegen when i pulled your pr in my local can you please check and sync your branch with latest changes .

Hello @samthakur587, I'm not sure why you're not seeing the files. Would you mind hopping on a quick discord call for this?

Screenshot 2024-08-26 at 5 16 23 PM
Screenshot 2024-08-26 at 5 24 42 PM

**Comment by samthakur587** [comment]
> > hii @AxelB1011 there is no test files for codegen when i pulled your pr in my local can you please check and sync your branch with latest changes .
> 
> Hello @samthakur587, I'm not sure why you're not seeing the files. Would you mind hopping on a quick discord call for this?
> Screenshot 2024-08-26 at 5 16 23 PM Screenshot 2024-08-26 at 5 24 42 PM

sure @AxelB1011  ping on discord when you'r free to have a call . hope we can fix it  togather .

**Pull request closed without merging**
