### PR TITLE
Update test_parser.py

### PR DESCRIPTION
**Pull request by Sambit712**
1.Anticipated AST:

A. For the condition "(a > 1)," the test anticipates a "IfNode" with a "BinaryOpNode," followed by a body that includes the "doSomething()" function call (represented as a "FunctionCallNode"). B. The else if block is handled recursively as an additional "IfNode," including a function call ( "doSomethingElse()") and its own condition "(a < 0)". C. The function call for "fallback()" is contained in the else block.

2. Assistance Nodes:

A. To compare nodes in the test, the "IfNode," "BinaryOpNode," "VariableNode," and "FunctionCallNode" classes are defined with "__eq__" methods. B. The structure that your parser outputs must match these nodes.

3. FunctionCallNode: 

This node symbolises a call to a function, such as "fallback()" or "doSomething()." If your parser generates a different structure for function calls, you should modify this node definition.

Make that the 'IfNode,' 'BinaryOpNode,' and 'VariableNode' are generated appropriately and that your 'GLSLParser' can construct 'FunctionCallNode' objects for function calls.

After you're satisfied the parser is operating correctly run the test using: python -m unittest test_glsl_parser.py

### shader Sample
<!-- Provide a shader sample or snippet on which you have tested your changes. like

```crossgl
shader PerlinNoise {
    vertex {
        input vec3 position;
        output vec2 vUV;

        void main() {
            vUV = position.xy * 10.0;
            gl_Position = vec4(position, 1.0);
        }
    }

    // Perlin Noise Function
    float perlinNoise(vec2 p) {
        return fract(sin(dot(p, vec2(12.9898, 78.233))) * 43758.5453);
    }

    // Fragment Shader
    fragment {
        input vec2 vUV;
        output vec4 fragColor;

        void main() {
            float noise = perlinNoise(vUV);
            float height = noise * 10.0;
            vec3 color = vec3(height / 10.0, 1.0 - height / 10.0, 0.0);
            fragColor = vec4(color, 1.0);
        }
    }
}
```-->


### Checklist
- [x] Have you added the necessary tests?
- [x] Only modified the files mentioned in the related issue(s)?
- [ ] Are all tests passing?

### CODE REVIEW

**Comment by samthakur587** [comment]
hii @Sambit712 it's great that you have worked on this but as of now we are do not adding the assert for all node in parser bcz it is too complicated to write assert for each node. currently there are short test example but if you write a complete  code for a shader than it has so many nodes in ast writing  assert for each node is very difficult. 

we have a different pipeline that check that example in more detail in developing stage. we are not doing the way you write this .

**Comment by samthakur587** [comment]
you can checkout this #89 todo list and assign yourself a task that you feel confident and start working on it .

**Comment by Sambit712** [comment]
Sir may I check out this problem or should I try adding the tests?

**Comment by samthakur587** [comment]
hii @Sambit712 if you go through this merged PR #104 then you will understand how to add the tests not like you added .

**Pull request closed without merging**
