### PR TITLE
Add else if to translator #32

### LINKED ISSUE #32: Add `else if `  Conditional Statements to the translator
To add `else if` support to CrossGL, modify the following files in the `crosstl/src/translator` directory:

- [ ] **Lexer.py**: Add token recognition for `else if`.
- [ ] **Parser.py**: Update grammar and AST to handle `else if`.
- [ ] **Directx_codegen.py**: Implement `else if` for HLSL output.
- [ ] **Metal_codegen.py**: Implement `else if` for Metal output.
- [ ] **Opengl_codegen.py**: Implement `else if` for GLSL output. 

Your contribution is appreciated! Feel free to reach out on our [Discord Server ](https://discord.com/invite/uyRQKXhcyW) if you have any query.

### LINKED ISSUE #48: Add `Assignment AND`  Token at translator frontend
Implement the ASSIGN_AND token to recognize the &= operator for performing bitwise AND assignments.

### PR DESCRIPTION
**Pull request by AxelB1011**
- **Added else if to translator**
- **Removed comment(s)**
- **[pre-commit.ci] auto fixes from pre-commit.com hooks**
- **added else if support to Directx backend**
- **added Assignment and, assignment or, assignment xor, xor , assignemnt modulus and modulus to the translator frontend. closes #48,#50,#51,#52,#53**
- **tests for else_if added**
- **[pre-commit.ci] auto fixes from pre-commit.com hooks**
- **[pre-commit.ci] auto fixes from pre-commit.com hooks**
- **Implement tokens for unsigned int and double data types (#68)**
- **fix for multiple else if conditionals**
- **Implement a very basic parser for simple Mojo syntax.**
- **more fixes for multiple else if conditionals**
- **More fixes**
- **Missing newline**
- **fix CI error**
- **fix CI error**
- **Refactored Logical Operation token in Translator Frontend (#91)**
- **Removed name=main**

### PR Description
Modified the following files in the crosstl/src/translator directory:

 parser.py: Updated the the parse_if_statement() function.
 directx_codegen.py: Implemented else if for HLSL output.
 metal_codegen.py: Implemented else if for Metal output.
 opengl_codegen.py: Implemented else if for GLSL output.
 test_lexer.py, test_parser.py, test_directx_codegen.py, test_metal_codegen.py, test_opengl_codegen.py: Added tests for multiple else if conditionals in test_translator and test_translator/test_codegen.

### Related Issue
Closed #32

### shader Sample
```crossgl
shader PerlinNoise {
    vertex {
        input vec3 position;
        output vec2 vUV;

        void main() {
            vUV = position.xy * 10.0;
            if (vUV.x < 0.5) {
                vUV.x = 0.25;
            }
            if (vUV.x < 0.25) {
                vUV.x = 0.0;
            } else if (vUV.x < 0.75) {
                vUV.x = 0.5;
            } else if (vUV.x < 1.0) {
                vUV.x = 0.75;
            } else {
                vUV.x = 0.0;
            }
            gl_Position = vec4(position, 1.0);
        }
    }

    // Fragment Shader
    fragment {
        input vec2 vUV;
        output vec4 fragColor;

        void main() {
            if (vUV.x > 0.75) {
                fragColor = vec4(1.0, 1.0, 1.0, 1.0);
            } else if (vUV.x > 0.5) {
                fragColor = vec4(0.5, 0.5, 0.5, 1.0);
            } else if (vUV.x > 0.25) {
                fragColor = vec4(0.25, 0.25, 0.25, 1.0);
            } else {
                fragColor = vec4(0.0, 0.0, 0.0, 1.0);
            }
            fragColor = vec4(color, 1.0);
            }
        }
    }
```

### Checklist
- [x] Have you added the necessary tests?
- [x] Only modified the files mentioned in the related issue(s)?
- [x] Are all tests passing?

### CODE REVIEW

**Comment by AxelB1011** [comment]
@samthakur587  I have create a new PR as per your advice. Please let me know if this is alright

**Comment by samthakur587** [comment]
hii @AxelB1011 great work so far just one last thing to fix . let's assume you have two continues `if` statements how do you handle this . the parser  not parse this second if state. 

can you try this example code for test your code .

```
shader PerlinNoise {
    vertex {
        input vec3 position;
        output vec2 vUV;

        void main() {
            vUV = position.xy * 10.0;
            if (vUV.x < 0.5) {
                vUV.x = 0.25;
            }
            if (vUV.x < 0.25) {
                vUV.x = 0.0;
            }
            
            } else if (vUV.x < 0.75) {
                vUV.x = 0.5;
            } else {
                vUV.x = 0.0;
            }
            gl_Position = vec4(position, 1.0);
        }
    }

    // Fragment Shader
    fragment {
        input vec2 vUV;
        output vec4 fragColor;

        void main() {
            if (vUV.x > 0.75) {
                fragColor = vec4(1.0, 1.0, 1.0, 1.0);
            } else if (vUV.x > 0.5) {
                fragColor = vec4(0.5, 0.5, 0.5, 1.0);
            } else {
                fragColor = vec4(0.0, 0.0, 0.0, 1.0);
            }
            fragColor = vec4(color, 1.0);
            }
        }
    }

```

**Comment by samthakur587** [comment]
you can take reference from this PR . i fixed this issue here . #39

**Comment by AxelB1011** [comment]
> hii @AxelB1011 great work so far just one last thing to fix . let's assume you have two continues `if` statements how do you handle this . the parser not parse this second if state.
> 
> can you try this example code for test your code .
> 
> ```
> shader PerlinNoise {
>     vertex {
>         input vec3 position;
>         output vec2 vUV;
> 
>         void main() {
>             vUV = position.xy * 10.0;
>             if (vUV.x < 0.5) {
>                 vUV.x = 0.25;
>             }
>             if (vUV.x < 0.25) {
>                 vUV.x = 0.0;
>             } else if (vUV.x < 0.75) {
>                 vUV.x = 0.5;
>             } else {
>                 vUV.x = 0.0;
>             }
>             gl_Position = vec4(position, 1.0);
>         }
>     }
> 
>     // Fragment Shader
>     fragment {
>         input vec2 vUV;
>         output vec4 fragColor;
> 
>         void main() {
>             if (vUV.x > 0.75) {
>                 fragColor = vec4(1.0, 1.0, 1.0, 1.0);
>             } else if (vUV.x > 0.5) {
>                 fragColor = vec4(0.5, 0.5, 0.5, 1.0);
>             } else {
>                 fragColor = vec4(0.0, 0.0, 0.0, 1.0);
>             }
>             fragColor = vec4(color, 1.0);
>             }
>         }
>     }
> ```

Thank you for the feedback @samthakur587! I have used the above code for reference and updated the tests. The parser seems to be working fine, unless I am missing something..?

**Review by samthakur587 — APPROVED** [review]
hii @AxelB1011 really a great work everything  LGTM 🚀  

Thanks for your contribution

**Pull request merged**
