### PR TITLE
Add Support for bitwise OR opeator(|) token in translator codegen frontend #107 

### PR DESCRIPTION
**Pull request by mr-195**
### PR Description

New PR ( similar to PR #154 ) after resolving conflict with the main branch.
- **Feature**: Added support for the **Bitwise OR** token (`|`) in the translator frontend, addressing issue **#107**. This ensures proper translation across the DirectX, Metal, and OpenGL backends.
- **Fix**: Resolved a minor issue in `crosstl/crosstl/src/translator/parser.py`, where `"ASSIGN_SHIFT_LEFT"` and `"ASSIGN_SHIFT_RIGHT"` were mistakenly placed on the same line without a comma.
- **Maintenance**: Updated `.gitignore` to remove unnecessary files from the project, streamlining the repository.

### Related Issue
#107 

### shader Sample

```crossgl
shader OrTestShader {
    vertex {
        input vec3 position;
        output vec2 vUV;

        void main() {
            // Perform OR on the x and y components of the position
            vUV.x = float(int(position.x) | 3);  // OR with 3
            vUV.y = float(int(position.y) | 5);  // OR with 5
            gl_Position = vec4(position, 1.0);
        }
    }

    fragment {
        input vec2 vUV;
        output vec4 fragColor;

        void main() {
            // Use OR in fragment shader
            float result = float(int(vUV.x) | int(vUV.y));
            fragColor = vec4(result / 10.0, 1.0 - result / 10.0, 0.0, 1.0);
        }
    }
    }
```

### Checklist
- [x] Have you added the necessary tests?
- [ ] Only modified the files mentioned in the related issue(s)?
- [x] Are all tests passing?

### CODE REVIEW

**Comment by samthakur587** [comment]
hii @mr-195 can you please resolve the merge conflicts

**Comment by mr-195** [comment]
Sure, I'll do it right away

**Comment by samthakur587** [comment]
hii @mr-195 the test are not passing [here](https://github.com/CrossGL/crosstl/actions/runs/10929779584/job/30341237198?pr=157#step:5:44) can you please have a look on this.

**Comment by mr-195** [comment]
Definitely, I am looking into this. I'll raise a new pr if it doesn't work.

**Pull request closed without merging**
