### PR TITLE
#193 - Add support for switch-case statements in DirectX backend

### LINKED ISSUE #193: switch statement

### PR DESCRIPTION
**Pull request by RatneshKJaiswal**
### PR Description

- Updated DirectxLexer.py to tokenize `switch`, `case`, and `default` keywords.
- Modified DirectxParser.py to parse `switch-case` constructs into `SwitchNode` and `CaseNode` AST representations.
- Added `SwitchNode` and `CaseNode` to DirectxAst.py to model the syntax tree for switch-case statements.
- Enhanced DirectxCrossGLCodeGen.py to generate GLSL code for `switch-case` constructs.

### Related Issue

Closes #193

### shader Sample

shader SwitchCaseSample {
    fragment {
        input int value;
        output vec4 color;

        void main() {
            switch (value) {
                case 1:
                    color = vec4(1.0, 0.0, 0.0, 1.0);
                    break;
                case 2:
                    color = vec4(0.0, 1.0, 0.0, 1.0);
                    break;
                default:
                    color = vec4(0.0, 0.0, 1.0, 1.0);
                    break;
            }
        }
    }
}

- Created and updated tests:
  - `test_lexer.py` to validate tokenization of `switch-case` statements.
  - `test_parser.py` to verify parsing of `switch-case` constructs.
  - `test_codegen.py` to ensure correct GLSL code generation for `switch-case`.

### Checklist
- [done] Have you added the necessary tests?
- [done] Only modified the files mentioned in the related issue(s)?
- [done] Are all tests passing?

### CODE REVIEW

**Comment by NripeshN** [comment]
Hi @RatneshKJaiswal
Could you please resolve the merge conflicts

**Comment by RatneshKJaiswal** [comment]
Merge Conflict Resolved

**Review by NripeshN — APPROVED** [review]

**Comment by NripeshN** [comment]
Please resolve the merge conflicts again, once done ready to merge

**Review by NripeshN — APPROVED** [review]

**Pull request merged**
