### PR TITLE
Assignment tokens

### LINKED ISSUE #48: Add `Assignment AND`  Token at translator frontend
Implement the ASSIGN_AND token to recognize the &= operator for performing bitwise AND assignments.

### LINKED ISSUE #50: Add `Assignment OR`  Token at translator frontend
Implement the ASSIGN_OR token to recognize the |= operator for performing bitwise OR assignments.

### LINKED ISSUE #51: Add `Assignment XOR`  Token at translator frontend
Implement the ASSIGN_XOR token to recognize the ^= operator for performing bitwise XOR assignments.

### LINKED ISSUE #52: Add `Assignment Modulus`  Token at translator frontend
Implement the ASSIGN_MOD token to recognize the %= operator for performing modulus assignments.

### LINKED ISSUE #53: Add `Modulus`  Token at translator frontend
Implement the MODULO token to recognize the % operator for calculating remainders.

### PR DESCRIPTION
**Pull request by Proxihox**
### PR Description
Added Assignment and, assignment or, assignment xor, xor , assignemnt modulus and modulus to the translator frontend.
Also wrote a test function for the lexer for most of the operators and assignment operators.
### Related Issue
closes #48
closes #50 
closes #51 
closes #52 
closes #53 

### shader Sample
"""
    int a = 1;
    a += 1;
    a *= 2;
    a /= a;
    a -= -1;
    a %= 2;
    a &= 1;
    a |= 1;
    a ^= 1;
    """

Side note: I must have mistakenly included the changes in 'translator/lexer.py' in my previous pull request so its not showing up as a change here.

### CODE REVIEW

**Comment by NripeshN** [comment]
Hi @Proxihox 
Could you pease resolve the merge conflicts

**Review by samthakur587 — CHANGES_REQUESTED** [review]
hii @Proxihox  you only added the tests where is actual changes for the translator laxer .  can you please add those also.

**Comment by Proxihox** [comment]
Hi @samthakur587 , I mentioned a sidenote at the end of my PR. Lines 48,49,50,55 and 56 of 'lexer.py' already have the code from my previous PR. I'll try to avoid such confusions from happening next time.

**Review by samthakur587 — APPROVED** [review]
hii @Proxihox  yeah only tests are needed the tokens are already there . your tests are generating correct tokens . thanks for adding the tests . 

everything LGTM 🚀

**Pull request merged**
