### PR TITLE
updated opengl module to add else if support

### LINKED ISSUE #35: Add `else if` Conditional Statements to the Opengl backend
To add `else if` support to CrossGL, modify the following files in the `crosstl/src/backend/Opengl` directory:

- [ ] **OpenglLexer.py** : Add token recognition for `else if`.
- [ ] **OpenglParser.py** : Update grammar and AST to handle `else if`.
- [ ] **openglCrossglCodegen.py** : Implement `else if` for Crossgl output.

Your contribution is appreciated! Feel free to reach out on our [Discord Server ](https://discord.com/invite/uyRQKXhcyW) if you have any query.

### PR DESCRIPTION
**Pull request by Sahil06012002**
**Refactor OpenGL Code Generation to Handle else if Chains.**
1. Modified GLSLLexer Class to tokenize the else if keywords correctly.
2. Added parse_else_if_chain method to handle multiple else if branches and an optional else block.
3. **AST Update**: Modified the Abstract Syntax Tree (AST) structure to support else if nodes, ensuring correct hierarchical representation of nested conditional logic.
4.**Updated generate_if Method in GLSLToCrossGLConverter** : Includes logic for generating multiple else if branches and an optional else block.

Closes #35

### CODE REVIEW

**Comment by Sahil06012002** [comment]
Please let me know if there needs to be any modification.

**Comment by NripeshN** [comment]
> **Refactor OpenGL Code Generation to Handle else if Chains.**
> 
> 1. Modified GLSLLexer Class to tokenize the else if keywords correctly.
> 2. Added parse_else_if_chain method to handle multiple else if branches and an optional else block.
> 3. **AST Update**: Modified the Abstract Syntax Tree (AST) structure to support else if nodes, ensuring correct hierarchical representation of nested conditional logic.
>    4.**Updated generate_if Method in GLSLToCrossGLConverter** : Includes logic for generating multiple else if branches and an optional else block.

Closes #35

**Review by samthakur587 — CHANGES_REQUESTED** [review]
Hii @Sahil06012002 can you write the tests also for else_if statement just to make sure all are passing. You can find the test files are in tests folder take reference from if condition test . 

Thanks

**Comment by Sahil06012002** [comment]
Okay @samthakur587, I'll add the tests as well.

**Comment by Sahil06012002** [comment]
Hi @samthakur587 ,
I have implemented the requested changes and added the following:
**Test Cases:**
Added a new test function for the else if condition in both test_lexer.py and test_parser.py.
Integrated the else if test case into the existing function in test_codegen.py to avoid repetition.
**Passing Tests:**
All test cases, including the new ones, are passing.
**Code Updates:**
Updated the parse_if() function in OpenglParser.py to ensure compatibility with the test cases.
Please review the changes and let me know if any further adjustments are needed in terms of logic or structure.

**Review by samthakur587 — APPROVED** [review]
great work @Sahil06012002 👍🏾 

everything LGTM 🚀

**Comment by samthakur587** [comment]
can you please sync your branch to latest changes . it's ready to merge 🚀

**Comment by Sahil06012002** [comment]
Hello @samthakur587 , I just merged the CrossGL:main branch, this branch now includes the latest changes, can you please check.

**Review by NripeshN — APPROVED** [review]
LGTM!!🚀

**Pull request merged**
